### ISSUE TITLE
PDOException 

### ISSUE THREAD

**Issue by aleixo2022** [KKSzymanowski/laravel-6-odbc#11]
after configured the system keeps throwing an exception. So I uncommented the pdo_odbc in php.ini. but nothing has changed.
My settings below:

DB_ODBC_CONNECTION_STRING="odbc:DRIVER=Pervasive;ServerName=10.1.1.1;DBQ=D:/Sys/Base/BASE;UID=SYSDBA;PWD=masterkey"
DB_ODBC_HOST=10.1.1.1
DB_ODBC_DATABASE=D:/Sys/Base/BASE
DB_ODBC_USERNAME=SYSDBA
DB_ODBC_PASSWORD=masterkey

and my query below:
 `$results = DB::connection('myOdbcConnection')->select('SELECT product, cod_product, descricao1 FROM PRODUCTS WHERE produto = :p', ['p' => 10633681]);`

My model:
`  protected $connection = 'myOdbcConnection';
  protected $table ='products';

  protected $fillable =[
    'PRODUCT', 'COD_PRODUCT', 'DESCRICAO1'
];`

**Comment by KKSzymanowski** [comment]
What's the exception message?

**Comment by aleixo2022** [comment]
> ![image](https://user-images.githubusercontent.com/72424790/149340472-e6851556-3ab6-429f-99b9-c8d454d08f53.png)

**Comment by KKSzymanowski** [comment]
Sorry, I can't help if there's no exception message. PDOException almost always suggests there's a problem with the database or the ODBC driver, not with this package. I have no problems connecting to Pervasive databases.

**Comment by aleixo2022** [comment]
sorry, below:
![image](https://user-images.githubusercontent.com/72424790/149341267-f051e721-f7db-4ee7-9019-4538890449f0.png)

**Comment by KKSzymanowski** [comment]
That's the line where the error occurred, not the message. Check the logs in storage/logs, maybe it's there.

**Comment by aleixo2022** [comment]
Datasource name not found and no default driver specified
![image](https://user-images.githubusercontent.com/72424790/149342216-bd2abb46-c7c5-46f0-bb00-434b38e07498.png)

**Comment by KKSzymanowski** [comment]
Sounds like you didn't configure the ODBC driver correctly. I don't have a windows PC on hand by I'll check what the configuration should look like later today

What version of Pervasive DB are you connecting to?

**Comment by aleixo2022** [comment]
I'm not using this manager... could this be my mistake? because I already use Ibeexpert to manage the DB.

**Comment by KKSzymanowski** [comment]
IBExpert is used to connect to a Firebird database. What database engine and version are you using?

**Comment by aleixo2022** [comment]
I'm using DB with firebird 2.5 version 2.5.927139
i am connected by ibeexpert via a vpn using odbc driver Firebird/Interbase(r) version 2.00.05.156.
With Ibeexpert it works.

**Comment by KKSzymanowski** [comment]
Ok then first of all `DRIVER=Pervasive` in your connection string makes no sense to me if you're connecting to a Firebird database.

Second, if you're connecting to Firebird 2.5 I've got a package just for that: https://github.com/KKSzymanowski/laravel-6-firebird
It works with Laravel >=6 and uses pdo_firebird extension in PHP.
You should use that instead, it's much easier than configuring the ODBC connection.

**Comment by aleixo2022** [comment]
Will yours work even on remote connections?

**Comment by KKSzymanowski** [comment]
Yeah I always use remote connections and have no issues. If IBExpert works from your PC to the database thorugh the VPN then PHP will also be able to connect.

**Comment by aleixo2022** [comment]
I tested here really you are right it worked well!
Thank you very much and congratulations for your work!
