### ISSUE TITLE
KKSzymanowski / laravel-6-odbc not working With Eloquent

### ISSUE THREAD

**Issue by afrostreet** [KKSzymanowski/laravel-6-odbc#2]
Hi,

I have used this for ODBC connection in laravel but its not working when i use it Eloquent.
I follow the steps the you have mention in the release.

I used  $users = DB::connection('myOdbcConnection')->table('User')->select('*')->get();

giving the following error:

Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 0 [SAP AG][LIBODBCHDB DLL][HDBODBC] Base table or view not found;259 invalid table name: Could not find table/view Users in schema B1ADMIN: line 1 col 15 (at pos 14) (SQLPrepare[0] at ext\pdo_odbc\odbc_driver.c:206) (SQL: select * from "Users")

And its working if i use- $user = DB::connection('myOdbcConnection')->select("Select * From FF_TEST.\"Users\"");

Please help me.

**Comment by KKSzymanowski** [comment]
> I used $users = DB::connection('myOdbcConnection')->table('**User**')->select('*')->get();
> [...]
> And its working if i use- $user = DB::connection('myOdbcConnection')->select("Select * From FF_TEST."**Users**"");

So is is User or Users? 🙂

**Comment by KKSzymanowski** [comment]
Have you resolved your issue?
