### ISSUE TITLE
use SqlServerGrammar  

### ISSUE THREAD

**Issue by mesak** [KKSzymanowski/laravel-6-odbc#3]
```

        'odbc' => [
            'grammar' => [
                'query' => Illuminate\Database\Query\Grammars\SqlServerGrammar::class,
                'schema' => Illuminate\Database\Schema\Grammars\SqlServerGrammar::class,
            ]
        ]

```

**Comment by KKSzymanowski** [comment]
Can you provide a little bit more context to your issue? I think you can connect to Microsoft SQL Server from Laravel out of the box, you don't need this package.

**Comment by mesak** [comment]
I use this package to connect to sybase, using laravel  SqlServerGrammar can work normally

Thanks for the kit
