### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by rcrespowin** [KKSzymanowski/laravel-6-odbc#6]
Hi there,

I was wondering if this ODBC driver will be compatible with PHP 8 in the near future.

Thanks.

**Comment by KKSzymanowski** [comment]
I'll look into it, thanks for pointing it out.

**Comment by KKSzymanowski** [comment]
I have released a new version 6.0.5. It should be available on Packagist by now.

Can you check if everything works for you on PHP 8?

**Comment by rcrespowin** [comment]
It worked like a charm.

Laravel 8, PHP 8 and SAP HANA 9.3

Thank you so much.
