### ISSUE TITLE
ODBC Driver does not support lastInsertId()

### ISSUE THREAD

**Issue by murbagus** [KKSzymanowski/laravel-6-odbc#8]
Hello..
I'm using this package for connecting my Laravel 7.29 project to my database (SQL Anywhere)
My database table have an id with auto incrementing,, but I'm getting this error whenever I wanna use MyModel::create([]) method (insert row)

`PDOException: SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId() in /var/www/api/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/SqlServerProcessor.php:29`

**Comment by KKSzymanowski** [comment]
Sorry, but this is beyond my power. The PHP ODBC driver simply does not support `lastInsertId()` and I cannot do anything about it.

I see you're using `SqlServerProcessor`. Keep in mind that Laravel supports connecting to Microsoft SQL Server out of the box, without the need of ODBC extension in PHP or this package.
https://laravel.com/docs/8.x/database#mssql-configuration

**Comment by murbagus** [comment]
> Sorry, but this is beyond my power. The PHP ODBC driver simply does not support `lastInsertId()` and I cannot do anything about it.
> 
> I see you're using `SqlServerProcessor`. Keep in mind that Laravel supports connecting to Microsoft SQL Server out of the box, without the need of ODBC extension in PHP or this package.
> https://laravel.com/docs/8.x/database#mssql-configuration

Thanks for your respons.. 
That was a bad news 🤦‍♂️
Actually I'm not using Microsoft SQL Server,, I'm using SQL Anywhere as my RDBMS so that is why I used ODBC

Fortunately, I found a simple solution for my simple case
I just customize the post processor used in my ODBC connection..
My custom class processor extend the default laravel database query processor,, and create this method inside it

```php
    public function processInsertGetId(Builder $query, $sql, $values, $sequence = null)
    {
        $connection = $query->getConnection();

        $connection->insert($sql, $values);

        $result = $connection->selectFromWriteConnection(
            'SELECT @@IDENTITY AS id'
        );

        $row = $result[0];
        $id = $row->id;

        return is_numeric($id) ? (int) $id : $id;
    }
```

I know this is not the best and kinda weird solution,, and I don't know the side effects of this solution,, but after all this is work for me hahaha 😂

**Comment by KKSzymanowski** [comment]
I haven't ever used SQL Anywhere but this code looks like you can run into some race conditions where between inserting the new row and checking its id someone else inserts their new row and you get their id. If it isn't something you should be concerned about then go ahead but it's something to keep in mind.

**Comment by KKSzymanowski** [comment]
Also, if it's something you have under control, I would strongly recommend using some popular database engine like MySQL, PostgreSQL etc. Using something less known like SQL Anywhere, which I haven't ever heard of, can cause many issues along the way.
